### PR TITLE
Add latest version 2.3.3

### PR DESCRIPTION
**Pull request by jamesmstone**
You may also have to add a new tag on [docker hub](https://hub.docker.com/r/yongjhih/android-studio/)

### CODE REVIEW

**Comment by jamesmstone** [comment]
Sorry, I don't think you updated the tags for the automated builds on [docker hub](https://hub.docker.com/r/yongjhih/android-studio/) I'd greatly appreciate it if you could, add a `2.3` tag but alos update the `latest` tag 
cheers :tada:

**Comment by yongjhih** [comment]
Hi @jamesmstone,
No, I didn't update the tags for that yet. Thanks for reminding me, I'm going to push tag for automated build on docker hub. But, I just realized that automated build error for latest tag, I need figure it out what's going on for a while.

**Comment by jamesmstone** [comment]
I think you might have to change [this](https://github.com/yongjhih/docker-android-studio/blob/1549b3b8adca54d22d78aa8cca0ebd89e14ef284/Dockerfile#L3) to
```
RUN dpkg --add-architecture i386 && \
apt-get update && apt-get install -y --no-install-recommends sudo lib32z1 lib32ncurses5 lib32stdc++6 lib32z1 lib32ncurses5 lib32stdc++6 && \
```

**Comment by jamesmstone** [comment]
ping :P ..Sorry

**Pull request merged**
